CONSTRUCT {
    ?s ?p ?o .
}
WHERE {
    {tw:Motor_defaultShape (sh:property|sh:node|sh:and)+ ?shape .} 
    UNION { bind (tw:Motor_defaultShape as ?shape)}
    
    {
        ?shape ?p ?o .
        BIND(?shape AS ?s)
    } UNION {
        ?shape ?p1 ?UoM_property .
        ?UoM_property sh:path tw:hasUnitOfMeasure .
        ?UoM_property sh:class ?UnitsOfSomeM .
        ?s ?p ?UnitsOfSomeM. 
        BIND(?UnitsOfSomeM AS ?o)
    } UNION {
        ?shape (sh:in|sh:and) ?list .
        ?list (rdf:first|rdf:rest)+ ?listNodes .
        ?listNodes ?p ?o .
        BIND(?listNodes AS ?s)
    } 
}